package com.ozo.expenseGenerator.constant;

public enum ExpenseDescriptions {
    MACARONI, PIZZA, BURGER, FRIED_RICE, CHICKEN, BEEF, PORK, FISH, VEGETABLES, FRUITS, BREAD, CAKE, ICE_CREAM, COFFEE,
    TEA, JUICE, SODA, WATER, BEER, WINE, WHISKEY, VODKA, RUM, GIN, BRANDY, COGNAC, LIQUEUR, CIDER, SAKE, SOJU, SHOCHU,
    MAEJU, BAIJU, ARAC, ARAK, RAKI, OUZO, SAMBU
}
