version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    hostname: namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - cluster-network

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    restart: always
    hostname: localhost
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9864:9864
    networks:
      - cluster-network
 
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - cluster-network
 
  nodemanager1:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - cluster-network

  firefox:
    image: jlesage/firefox
    hostname: firefox
    ports:
      - 5800:5800
    networks:
      - cluster-network
  
  historyserver:
    image: bde2020/hadoop-historyserver:latest
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - cluster-network

  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/data/postgres
    networks:
      - cluster-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    hostname: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cluster-network

  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    restart: always
    ports:
      - 8121:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "SPARK_MASTER_HOST=spark-master"
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./spark_data:/spark/data
    networks:
      - cluster-network

  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    hostname: spark-worker
    restart: always
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    env_file:
      - ./hadoop.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - cluster-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cluster-network

  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "9094:9094"  # Expose 9094 for PLAINTEXT_HOST
    networks:
      - cluster-network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  cassandra-data:
  postgres_volume:

networks:
  cluster-network:
    driver: bridge
